### ISSUE TITLE
how to positon toasts

### ISSUE THREAD

**Issue by mwinner313** [paliari/v-toaster#8]
how can i position the toast for top-left ??

**Comment by paliari** [comment]
You can override CSS:
```css
.v-toaster {
  right: auto;
  left: 0;
}

```
